### PR TITLE
Add Unity.unity-debug using .vsix file

### PR DESCRIPTION
**Pull request by Awea**
Related to https://github.com/open-vsx/publish-extensions/pull/202#issuecomment-726019395

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, many thanks! 🚀

**Comment by jankeromnes** [comment]
This should successfully publish `Unity.unity-debug` tonight at around [03:03 UTC](https://github.com/open-vsx/publish-extensions/blob/b02685d6406c9d5b36676257979a2834ee92e76e/.github/workflows/publish-extensions.yml#L3-L6).

**Comment by jankeromnes** [comment]
@Awea Oh no, auto-publishing failed again, this time with:

```
Downloading https://github.com/Unity-Technologies/vscode-unity-debug/releases/download/Version-2.7.2/unity-debug-2.7.2.vsix
[FAIL] Could not process extension: {
  "id": "Unity.unity-debug",
  "download": "https://github.com/Unity-Technologies/vscode-unity-debug/releases/download/Version-2.7.2/unity-debug-2.7.2.vsix",
  "version": "2.7.2"
}
Error: Cannot resolve dependency: ms-vscode.csharp
```

And unfortunately, `ms-vscode.csharp` cannot be uploaded to OpenVSX because [its LICENSE](https://marketplace.visualstudio.com/items/ms-dotnettools.csharp/license) forbids it. 😕

**Comment by Awea** [comment]
index

@jankeromnes I'm sad to read this, should I remove this extension from the extensions.json file and forget about it?

**Comment by jankeromnes** [comment]
@Awea I'm not exactly sure. It's not a big issue to keep a failing extension in the list (the CI handles it pretty well) and I really hope that we'll be able to publish it some day. I don't like that non-Microsoft tools like VSCodium, Gitpod, Theia, Eclipse Che, etc cannot use some really cool open-source extensions like `Unity.unity-debug` just because of a bad dependency license.

One interesting question is how strongly tied to `ms-vscode.csharp` the `Unity.unity-debug` extension is, and whether it could also work with a different, not-Microsoft-only alternative (e.g. something like [free-omnisharp-vscode](https://github.com/muhammadsammy/free-omnisharp-vscode) maybe?)

Note that there is a similar discussion going on in https://github.com/platformio/platformio-vscode-ide/issues/1802 where the PlatformIO extension depends on `ms-vscode.cpptools` (which has a Microsoft-only license) but only for 5% of its features, so they're currently considering alternative dependencies to fix the license problem.

**Comment by Awea** [comment]
Hi @jankeromnes, thanks for the details. I neither don't like the fact that VSCodium can't use this extension because of some license issue. 

I'll try to ask on Unity.unity-debug if the extension can use a free alternative for csharp like you suggested :)

**Pull request merged**
