### PR TITLE
Update godot-vscode-plugin 1.0.1 to 1.1.2

### PR DESCRIPTION
**Pull request by do-kevin**
Hi,

I've never done this before. I would like to update godot-vscode-plugin from version 1.0.1 to 1.1.2.
The only download link I could find was [https://marketplace.visualstudio.com/_apis/public/gallery/publishers/geequlim/vsextensions/godot-tools/1.1.2/vspackage](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/geequlim/vsextensions/godot-tools/1.1.2/vspackage)

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @do-kevin, many thanks for updating godot-vscode-plugin!

> I've never done this before. I would like to update godot-vscode-plugin from version 1.0.1 to 1.1.2.

We generally download `.vsix` files from the extension's official GitHub releases.

However, in https://github.com/godotengine/godot-vscode-plugin/releases/ it seems that the latest official release is still 1.0.1 -- there appears to be no official release, branch or tag for 1.1.2

> The only download link I could find was https://marketplace.visualstudio.com/_apis/public/gallery/publishers/geequlim/vsextensions/godot-tools/1.1.2/vspackage

Unfortunately, the VSCode Marketplace from Microsoft explicitly forbids any non-Microsoft tools from using it in its terms of service. So we'll need to find a different source for godot-vscode-plugin's 1.1.2 .vsix file.

Could you please ask the maintainers where an unrestricted 1.1.2 .vsix release can be found?

**Comment by do-kevin** [comment]
Ah I see. It could take me a while to contact the maintainers; I'll see what I can do. Thanks!

**Comment by jankeromnes** [comment]
Thanks @do-kevin!

I see that there is a `1.1.2` release now in https://github.com/godotengine/godot-vscode-plugin/releases/ -- however, that release doesn't have a `.vsix` asset, so we still can't publish it.

Did you have any success in contacting the maintainers?

**Comment by jankeromnes** [comment]
On a side note, they could also just run `npx ovsx publish` (with a [OVSX_PAT](https://open-vsx.org/user-settings/tokens) token) when publishing to Microsoft's marketplace, and that would also publish to OpenVSX, VSCodium, Gitpod, etc. with just a single command & no dependencies. 🙂

**Comment by do-kevin** [comment]
@jankeromnes I did contact the repository owner via email. Though, I didn't get a reply, he published that release some days later. I've already sent him another email to include the .vsix file. As for maintainers, it seems they are currently looking for a new one.

I'll actually poke the repo owner later today to include the .vsix file. Hopefully, he does include it.

**Pull request closed without merging**
