### PR TITLE
Add 3 laravel extensions

### PR DESCRIPTION
**Pull request by BryanYeh**

### CODE REVIEW

**Comment by BryanYeh** [comment]
I did not mean to do 3 commits in 1 pull request. Still new to creating pull requests

**Review by jankeromnes — APPROVED** [review]
Hi @BryanYeh, many thanks for these really cool contributions! 💯 🙏

> I did not mean to do 3 commits in 1 pull request. Still new to creating pull requests

No worries, that's totally okay. 👍

As a maintainer, I have the option to "Squash and merge" your Pull Request, thus creating a single commit to be added to the main branch of this repository.

However, since your commits are clean & separate changes (each one adding a different extension), and they all have precise & relevant commit messages, I will instead go with a "Rebase and merge" option, thus adding your 3 separate commits to the main branch. (I find this slightly better in this case.)

Many thanks again! After I merge your Pull Request, our publishing script will attempt to auto-publish all three extensions tonight, and hopefully they will show up on https://open-vsx.org by tomorrow. 🙂

**Comment by jankeromnes** [comment]
Hi again @BryanYeh!

Both [codingyu.laravel-goto-view](https://open-vsx.org/extension/codingyu/laravel-goto-view) and [onecentlin.laravel5-snippets](https://open-vsx.org/extension/onecentlin/laravel5-snippets) got published to OpenVSX successfully! 🎉 Could you please confirm that both extensions work as expected?

However, auto-publishing of `stef-k.laravel-goto-controller` failed with this error:

```
Running: git clone --recurse-submodules https://github.com/stef-k/laravel-goto-controller /tmp/repository
Running: npm install
[FAIL] Could not process extension: {
  "id": "stef-k.laravel-goto-controller",
  "repository": "https://github.com/stef-k/laravel-goto-controller"
}
Error: Command failed: npm install
Error installing vscode.d.ts: Error: Request returned status code: 404
Details: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/releases/stable</pre>
</body>
</html>

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! laravel-goto-controller@0.0.13 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the laravel-goto-controller@0.0.13 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

This looks similar to https://github.com/microsoft/vscode/issues/120064 and might mean that the extension uses a too old version of `vscode`.

**Comment by BryanYeh** [comment]
Hi @jankeromnes
Both the extensions that were published works great.
Well that sucks `stef-k.laravel-goto-controller` ended up having trouble publishing.

**Comment by jankeromnes** [comment]
Many thanks for confirming @BryanYeh!

Also, the same bug affects other extensions, so I'm hopeful that we'll find a fix that works for all similarly failing extensions. 😊

**Pull request merged**
