### PR TITLE
Add `JannisX11.batch-rename`

### PR DESCRIPTION
**Pull request by stocyr**
- [X] I have read the note above about PRs contributing or fixing extensions
- [X] I have tried reaching out to the extension maintainers about publishing this extension to Open VSX (if not, please create an issue in the extension's repo using [this template](https://github.com/open-vsx/publish-extensions/blob/HEAD/docs/external_contribution_request.md)): see the [PR here](https://github.com/JannisX11/batch-rename/issues/8).
- [X] This extension has an [OSI-approved OSS license](https://opensource.org/licenses) (we don't accept proprietary extensions in this repository): [MIT](https://github.com/JannisX11/batch-rename/blob/main/LICENSE)

## Description

Added `JannisX11.batch-rename`

### CODE REVIEW

**Comment by filiptronicek** [comment]
Hi @stocyr 👋, thanks for the contribution. It seems that https://github.com/JannisX11/batch-rename does not use tags / releases, which does not sit well with our publishing system. Since the extension seems inactive, I will publish this manually and hopefully its author can publish subsequent releases.

**Comment by filiptronicek** [comment]
It seems that the build process is broken. @stocyr have you been able to package it yourself?

**Comment by stocyr** [comment]
@filiptronicek I didn't try to package it yet.

**Comment by filiptronicek** [comment]
@stocyr sadly I cannot get a working version of the extension myself and therefore cannot merge this PR now. Could you please mark it as a draft or close it until we have a way to build it? 🙏

**Comment by stocyr** [comment]
I forked the original project and updated a few dependencies -- got it to build successfully on [my own fork](https://github.com/stocyr/batch-rename).

A [PR](https://github.com/JannisX11/batch-rename/pull/14) is already filed, I hope the author reacts on it. Otherwise I suggest I publish my fork instead.

**Comment by filiptronicek** [comment]
@stocyr I am glad you have built it successfully on your fork. I will try packaging it myself and publishing it from there. In this case, I'm happy to publish under the original namespace of `JannisX11`, but I would also be happy if you'd like to publish it yourself under your own.

**Comment by stocyr** [comment]
@filiptronicek I suggest publishing under Jannis' namespace. I didn't really add anything to it honestly.

**Comment by stocyr** [comment]
@filiptronicek I just noticed that during our efforts, [this repo](https://github.com/DrInfinite/batch-rename) already created a copy (no fork, just a blank new commit) which independently published Batch-Rename to Open VSX..

Its required engine version is quite strict however (1.84.0). But publishing a duplicate is even less optimal.

**Comment by filiptronicek** [comment]
@stocyr it seems that although the name and icon are the same, the code is different, or at least added to. I think it still makes sense to publish the one you packaged, as one-time publishing will be useful for folks migrating from the VS Code Marketplace via ids.

> Its required engine version is quite strict however (1.84.0)

Since we are past the 1.85 release and the self-updating nature of VS Code, I wouldn't see this as too much of a problem.

**Comment by filiptronicek** [comment]
I've published it now: https://open-vsx.org/extension/JannisX11/batch-rename-extension

**Pull request closed without merging**
