### PR TITLE
Add rescript-vscode extension

### PR DESCRIPTION
**Pull request by bryphe**
Hi,

Just wanted to add this new `rescript` extension: https://github.com/rescript-lang/rescript-vscode

Thanks!

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, many thanks @bryphe! :+1:

**Comment by jankeromnes** [comment]
Update: Worked! 🎉 https://open-vsx.org/extension/chenglou/rescript-language-server

**Comment by jankeromnes** [comment]
Oh, but they seem to have deleted that release now: https://github.com/rescript-lang/rescript-vscode/releases/download/0.0.3/rescript-language-server-0.0.3.vsix

And in fact, they no longer publish any `.vsix` file 😐 https://github.com/rescript-lang/rescript-vscode/releases

Not sure why, or how we'll do to update this extension in the future.

**Comment by bryphe** [comment]
Ah, bummer - sorry about that @jankeromnes !

**Pull request merged**
