### PR TITLE
Implement 'add-extension.js' to simplify adding extensions

### PR DESCRIPTION
**Pull request by tennox**
## Description

A script to add the extension add correct position. Could later easily be modified to do some additional checks :sunglasses: 

Usage:
```bash
node add-extension.js ext.id https://github.com/x/y --optional arg
```

### CODE REVIEW

**Comment by filiptronicek** [comment]
Thanks for your contribution, @tennox! This is really useful and a way better experience than having to edit the JSON yourself, I will take a look at the code as soon as I get the chance 🙂.

**Comment by filiptronicek** [comment]
I have pushed some code style changes; code works great. Would be great to check if the arguments passed are valid properties according to the https://github.com/open-vsx/publish-extensions/blob/master/extensions-schema.json.

**Comment by filiptronicek** [comment]
> Would be great to check if the arguments passed are valid properties according to the master/extensions-schema.json.

@tennox would you be down to work on this as well? If not, I can for sure work on it, please don't feel forced to do it 😄.

**Comment by tennox** [comment]
Done :sunglasses:
- validate arg names
- validate arg value
```console 
$ node add-extension.js ext.id https://my-repo.org --location x --goo bar
argument 'goo' not found in ./extensions-schema.json
$ node add-extension.js ext.xcxid https://my-repo.org --location 5 --timeout=sg4
argument 'timeout' should be type 'number' but yours seems to be 'string'
```

(I decided to stringify any args so --location=5 will be `"5"`)

**Review by filiptronicek — APPROVED** [review]
LGTM, thank you for the contribution! 🧡

**Pull request merged**
