### PR TITLE
Add Rech Cobol Debugger extension

### PR DESCRIPTION
**Pull request by GustavoASC**
Hello,

May you merge this PR in order to add Rech Cobol Debugger extension, please?
Thanks in advance!

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @GustavoASC, many thanks for this contribution! 🙏

It would be awesome to have Rech Cobol Debugger on OpenVSX. 👀

However, just to avoid any misunderstandings:

1. Have you considered running `npx ovsx publish` yourself? (This is the best & most direct way to publish an extension to OpenVSX -- you can set it up as a GitHub Action, or simply run it manually once 👍)

2. If we merge this Pull Request as is, it will be an OpenVSX bot that simply clones your repository and runs `npx ovsx publish` in it every night -- this might accidentally publish work-in-progress / broken versions to OpenVSX (first uploaded version wins & remains unchanged). Is this really what you want? Alternatively, would you consider publishing official `.vsix` assets as GitHub Releases, or tagging each release with a dedicated Git tag we could pin here?

Happy to help either way! 😁 Please let me know if you have any questions.

**Comment by GustavoASC** [comment]
Hi @jankeromnes,

Yeah, you are right. I will try to use `npx ovsx publish` and after that I will close/cancel this PR, in case everything works fine.
Thank you very much for your attention!

**Comment by GustavoASC** [comment]
The extension is now published and can be found here:
https://open-vsx.org/extension/rechinformatica/rech-cobol-debugger

Again, thanks for your attention!

**Comment by jankeromnes** [comment]
That's awesome! 🎉 Many thanks @GustavoASC 💯

**Comment by brianking** [comment]
@GustavoASC I also recommend you claim ownership of the namespace for the extension, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace

**Pull request closed without merging**
