### PR TITLE
Add `stateful.issue-explorer`

### PR DESCRIPTION
**Pull request by christian-bromann**
- [x] I have read the note above about PRs contributing or fixing extensions
- [ ] I have tried reaching out to the extension maintainers about publishing this extension to Open VSX (if not, please create an issue in the extension's repo using [this template](https://github.com/open-vsx/publish-extensions/blob/HEAD/docs/external_contribution_request.md)).
- [x] This extension has an [OSI-approved OSS license](https://opensource.org/licenses) (we don't accept proprietary extensions in this repository)

## Description

This PR introduces X change for Y reason.

### CODE REVIEW

**Comment by christian-bromann** [comment]
> * I have tried reaching out to the extension maintainers about publishing this extension to Open VSX

I am the extension maintainer

**Review by filiptronicek — COMMENTED** [review]
Hi there @christian-bromann! I'm very happy that you'd like to publish your extension to Open VSX. Although this could work just fine, it would be really great if you could take a look at publishing this extension yourself and potentially integrating it via GitHub Actions. There's more info about this in [When to Add an Extension?](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension). 

Would this work for you?

**Comment by christian-bromann** [comment]
I have a GitHub Action doing this. I actually wrote [this article](https://www.stateful.com/blog/the-github-action-you-need-to-publish-vscode-extensions) about publishing to both registries. However it isn't really clear to me what is required to publish an extension to a certain organisation.

**Comment by christian-bromann** [comment]
Alright, so I got confused and thought adding the extension to the `extension.json` was needed to get it into the registry. I guess because a co-worker mentioned some month ago that there was still a manual step involved to get an extension registered. Anyway I got the extension published with the pipeline I described in my article: https://open-vsx.org/extension/stateful/issue-explorer

**Comment by filiptronicek** [comment]
Glad that it's there, @christian-bromann :). I am guessing the "manual step" that your co-worker mentioned would be claiming a namespace, which makes the extension marked as verified and also allows you to add multiple contributors / co-owners to this namespace. You can do this by raising an issue at https://github.com/EclipseFdn/open-vsx.org/issues/new/choose. Let me know if you need anything else!

**Pull request closed without merging**
