### PR TITLE
Add vscode-cyp

### PR DESCRIPTION
**Pull request by jonhue**
Hey, I'd love to have this package be published on Open VSX.

### CODE REVIEW

**Comment by jankeromnes** [comment]
> Hey, I'd love to have this package be published on Open VSX.

Hi @jonhue 👋 Sure! It would be awesome to have `vscode-cyp` on OpenVSX. 👍

But rather than auto-publishing it from this repository (which is kind of a workaround when maintainers cannot publish themselves, and has some unfortunate limitations) -- would you be interested in publishing `vscode-cyp` to OpenVSX yourself?

It's as easy as:

1. Getting a `OVSX_PAT` token from [here](https://open-vsx.org/user-settings/tokens)
2. Running `npx ovsx publish` (no dependencies required)

Please let me know if you have any questions or concerns, I'm happy to help. 🙂

**Comment by jonhue** [comment]
does osvx also work with yarn? 🙂

**Comment by jankeromnes** [comment]
> does osvx also work with yarn? 🙂

@jonhue Yes 🙂 `ovsx publish` accepts a `--yarn` flag:

```
$ ovsx publish --help
Usage: publish [options] [extension.vsix]

Publish an extension, packaging it first if necessary.

Options:
  [...]
  --yarn                   Use yarn instead of npm while packing extension files.
  [...]
```

**Comment by jankeromnes** [comment]
Many thanks @jonhue for publishing your extension to OpenVSX! 🎉 https://open-vsx.org/extension/jonhue/vscode-cyp

Please note that you can also claim the namespace `jonhue` as your own by opening an issue (see link in the yellow banner on your extension's OpenVSX page).

Let me know if there is anything else I can help with. 🙂

**Pull request closed without merging**
