### PR TITLE
include all language packs from vscode-loc

### PR DESCRIPTION
**Pull request by GitMensch**
hopefully fixing #117

### CODE REVIEW

**Review by spoenemann — APPROVED** [review]
Thanks!

**Comment by jankeromnes** [comment]
@GitMensch Auto-publishing worked! 🎉 https://open-vsx.org/?search=ceintl&category=&sortBy=relevance&sortOrder=desc

Except for `MS-CEINTL.vscode-language-pack-cs`, which failed with:

```
[FAIL] Could not process extension: {
  "id": "MS-CEINTL.vscode-language-pack-cs",
  "repository": "https://github.com/microsoft/vscode-loc",
  "location": "i18n/vscode-language-pack-cd"
}
Extension manifest not found: /tmp/repository/i18n/vscode-language-pack-cd/package.json
```

**Comment by GitMensch** [comment]
Yes, that's a typo. Can you please adjust this?

```diff
-  "location": "i18n/vscode-language-pack-cd"
+  "location": "i18n/vscode-language-pack-cs"
```

**Comment by GitMensch** [comment]
Another question @jankeromnes:

Shouldn't the MS-CEINTL packages have an identical note to ms-vscode/js-debug?

> The “JavaScript Debugger” extension was published by open-vsx.

As it stands the language packs have a note about "you may register that namespace" but #117 has a clear note "we don't want to publish to open-vsx as MS-CEINTL",

**Comment by jankeromnes** [comment]
Sure! I'll fix the typo, thanks for pointing it out.

> Shouldn't the MS-CEINTL packages have an identical note to ms-vscode.js-debug or ms-vscode.hexeditor?

I believe the different notes ("The namespace MS-CEINTL is public" vs "This user account is not related to the namespace ms-vscode of this extension") can be explained by the fact that the OpenVSX namespace `MS-CEINTL` has not been claimed by anyone yet (i.e. it's public), while `ms-vscode` has been claimed and assigned to a user (although I cannot find a corresponding issue in https://github.com/eclipse/open-vsx.org/issues, so I have no idea who claimed it -- @spoenemann do you know?)

> but #117 has a clear note "we don't want to publish to open-vsx as MS-CEINTL"

Apologies if I missed it, but who is "we" in this sentence?

Maybe to clarify, it is generally preferred that extension authors/owners/maintainers publish to https://open-vsx.org themselves (typically requires adding just one command, `npx ovsx publish`, to an existing CI/CD script). However, when that is not possible (for example, the authors are unresponsive / no longer active / not interested) we're happy to auto-publish popular open-source extensions from this repository (`open-vsx/publish-extensions`) as kind of a temporary workaround.

If/when the authors of `MS-CEINTL` extensions wish to take over the publishing of these extensions to OpenVSX, we would be more than happy to help make this happen, and to remove these extensions from our auto-publish list.

**Comment by spoenemann** [comment]
> I cannot find a corresponding issue in https://github.com/eclipse/open-vsx.org/issues, so I have no idea who claimed it

It was claimed non-publicly, see [How to Claim a Namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace).

**Pull request merged**
