### PR TITLE
Added cmake-tools and cpp-tools to extensions

### PR DESCRIPTION
**Pull request by kitattyor**
**cmake-tools** : Easily configure and build cmake based projects.

**cpp-tools**: intellisense and debugger frontend. Is platform specific, hence the multiple versions. Integrates well with cmake-tools.

### CODE REVIEW

**Comment by spoenemann** [comment]
The license of cpptools makes it impossible to use the extension in anything except Microsoft products, so we cannot accept the extension here:
https://github.com/microsoft/vscode-cpptools/blob/master/RuntimeLicenses/cpptools-LICENSE.txt

cmake-tools looks ok license-wise, but it has a dependency on cpptools:
https://github.com/microsoft/vscode-cmake-tools/blob/80a745aeb7a12c76f5976a7b4ebca9674d17b5dd/package.json#L1623

**Comment by herandol** [comment]
Does the RuntimeLicenses only apply to the .vsix provided by Microsoft or to all builds ?
I was thinking to build the extension in prepublish.

**Comment by spoenemann** [comment]
The extension also has runtime dependencies that it downloads on startup:

https://github.com/microsoft/vscode-cpptools/blob/9650bb7d9fba86d454847447aecb2450585ff330/Extension/package.json#L2290-L2527

I haven't checked, but I guess those are proprietary, too.

**Comment by spoenemann** [comment]
> Does the RuntimeLicenses only apply to the .vsix provided by Microsoft or to all builds ?

I don't know, you should ask the maintainers.

**Comment by kitattyor** [comment]
> 
> 
> The extension also has runtime dependencies that it downloads on startup:
> 
> https://github.com/microsoft/vscode-cpptools/blob/9650bb7d9fba86d454847447aecb2450585ff330/Extension/package.json#L2290-L2527
> 
> I haven't checked, but I guess those are proprietary, too.

Yes I now see that vscode-cpptools seems to be a MIT licensed wrapper around the cpp language service which cannot be used on anything other than Visual Studio / VSCode / Xamarin etc. 

As for cmake-tools, I recall that I built it without cpp tools and it worked fine. I think the reason why cmake-tools depends on cpp-tools is because cmake-tools updates the intellisense database. Still, configuring and building projects "should" work.

**Comment by spoenemann** [comment]
Ok, could you remove cpptools, then we'll merge cmake-tools?

**Comment by kitattyor** [comment]
Done .. Sorry for the delay..

**Comment by spoenemann** [comment]
Thanks! The remaining question is: shall we refer to a specific version and tag to ensure we publish only the officially released versions? In that case we would also need `version` and `checkout` properties as described in the README here.

An alternative is to just download a `vsix` file from the GitHub releases. I have seen the `vsix` packages are attached to the releases in the cmake-tools repository. In that case you can use the `download` property instead of `repository`.

**Comment by spoenemann** [comment]
So here are the two alternatives:
```json
    {
      "id": "microsoft.vscode-cmake-tools",
      "repository": "https://github.com/microsoft/vscode-cmake-tools",
      "version": "1.4.2",
      "checkout": "1.4.2"
    },
```
or
```json
    {
      "id": "microsoft.vscode-cmake-tools",
      "version": "1.4.2",
      "download": "https://github.com/microsoft/vscode-cmake-tools/releases/download/1.4.2/cmake-tools.vsix"
    },
```

**Comment by spoenemann** [comment]
The download variant is safer because we don't risk to mess up the package by doing something wrong in the build process.

**Comment by kitattyor** [comment]
Done :)

**Review by spoenemann — APPROVED** [review]
Thanks!

**Pull request merged**
