### PR TITLE
Added Haxe language related extensions

### PR DESCRIPTION
**Pull request by itzikiap**
I apologize for the commits mess. Please merge these extensions definitions to the extensions json. Thanks

### CODE REVIEW

**Comment by spoenemann** [comment]
Thanks for the contribution! Unfortunately `Haxe-Manager`, `vscode-kha` and `vscode-kha-extension-pack` have no license. I created the following issues regarding this:

https://github.com/Jarrio/Haxe-Manager/issues/17
https://github.com/Kode/vscode-kha/issues/25
https://github.com/Kode/vscode-kha-extension-pack/issues/2

but we have to wait until they are addressed before we can add those extensions to Open VSX.

`openfl.lime-vscode-extension` is duplicated, please remove one of those entries.

**Comment by mundusnine** [comment]
@itzikiap the [last extension](https://github.com/Jarrio/Haxe-Manager) that is holding back this being merged has not been updated in  years. Maybe we should remove it from this pull request for now and add it later or make it a separate pull request.

**Comment by jankeromnes** [comment]
@mundusnine Good idea, I agree.

@itzikiap Thanks again for your contribution! I took the liberty of:
1. rebasing your Pull Request
2. splitting `Jarrio/Haxe-Manager` out of your other changes
3. merging your other changes as https://github.com/open-vsx/publish-extensions/commit/4fb9ea371a1fa4ee26f792a817548b6b84a40b39

Now the only change that remains unmerged in this Pull Request is the `Jarrio/Haxe-Manager` extension without a license.

**Comment by jankeromnes** [comment]
Update: Auto-publishing `influrium.haxe-jsx` worked! 🎉 https://open-vsx.org/extension/influrium/haxe-jsx

But unfortunately, auto-publishing `nadako.vshaxe` failed with:

```
...
Version f3b99c4 configured in /tmp/repository/syntaxes/.haxerc does not exist. Attempting download ...
Looking up Haxe version "f3b99c4" online
  Resolved to nightly build f3b99c4. Downloading ...
Downloading Haxe: nightly build f3b99c4
-> Done!
  ... download complete!
/tmp/repository/syntaxes/haxe_libraries/yaml.hxml:1: classpath /home/runner/haxe/haxe_libraries/hx-yaml/0.0.0/github/a90c5a93ec8ca07bd73889c1707945e02903de8e/src is not a directory or cannot be read from
'npx haxe -lib yaml -lib plist -lib hxnodejs -cp src -debug -js bin/convert.js -main Converter' exited with 244
Failed to invoke `haxelib run-dir vshaxe-build /home/runner/haxe/haxe_libraries/vshaxe-build/0.0.1/github/de0c13838c4a8bad282ef8924aa71e34a315a245 -t vshaxe -t language-server-tests -t tm-language` because Error: Command failed: haxelib run-dir vshaxe-build /home/runner/haxe/haxe_libraries/vshaxe-build/0.0.1/github/de0c13838c4a8bad282ef8924aa71e34a315a245 -t vshaxe -t language-server-tests -t tm-language
npm ERR! code ELIFECYCLE
npm ERR! errno 244
npm ERR! vshaxe@2.22.0 vscode:prepublish: `npx lix run vshaxe-build -t vshaxe -t language-server-tests -t tm-language`
npm ERR! Exit status 244
npm ERR! 
npm ERR! Failed at the vshaxe@2.22.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-09-30T03_39_59_370Z-debug.log
[FAIL] Could not process extension: {
  "id": "nadako.vshaxe",
  "repository": "https://github.com/vshaxe/vshaxe.git"
}
npm failed with exit code 244
```

@spoenemann Do you know what this could mean / how this could be resolved?

Also, the other `nadako.vshaxe`-dependent extensions (i.e. `vshaxe.haxe-checkstyle`, `vshaxe.haxe-extension-pack`, `openfl.lime-vscode-extension`, `kodetech.kha` and `kodetech.kha-extension-pack`) could not be auto-published either. They all failed with:

```
Error: Cannot resolve dependency: nadako.vshaxe
```

**Comment by AlexHaxe** [comment]
I have just updated vshaxe's `package.json` to include a `npm install` call for it's `syntaxes` submodule (see https://github.com/vshaxe/vshaxe/commit/830fa4b20600d57e308410edd0b8cd89d03bb7d9). that should resolve your issue.

**Comment by jankeromnes** [comment]
@AlexHaxe Awesome, many thanks for the quick fix! 🙏

Also, FYI, in the long run it might make more sense if you (or other VSHaxe maintainers) publish VSHaxe to OpenVSX directly.

This repository is more of a temporary workaround to get popular open-source extensions published quickly, but it occasionally happens that (despite our best effort) we accidentally mess up packaging one or the other extension, leading to a broken upload to OpenVSX.

We're of course happy to continue doing our best to publish VSHaxe from here, but if you'd like to take over the publishing yourself, it could be just a matter of:
- adding the single command `npx ovsx publish` to an existing publishing script (e.g. the one for MS Marketplace -- `ovsx` is also based on `vsce`, and `npx` allows you to not install any dependency)
- setting up a `OVSX_PAT` env secret (you can get the value from [here](https://open-vsx.org/user-settings/tokens))

If that sounds interesting to you, I'd be more than happy to help set it up. 🙂

**Comment by jankeromnes** [comment]
Update: Ah, it seems that your fix was merged right in time before tonight's publish run, so VSHaxe was already published successfully to OpenVSX: https://open-vsx.org/extension/nadako/vshaxe 🎉

That should fix the publishing of the other dependent extensions in the next publish run. I'll report back if anything else is broken.

Thanks again!

**Comment by jankeromnes** [comment]
Good news everyone! All these extensions now also got auto-published successfully:

- https://open-vsx.org/extension/vshaxe/haxe-test-adapter
- https://open-vsx.org/extension/vshaxe/haxe-checkstyle
- https://open-vsx.org/extension/openfl/lime-vscode-extension
- https://open-vsx.org/extension/kodetech/kha

The extension `kodetech.kha-extension-pack` failed, but the error looks more like an internal problem with this repository, and once resolved I believe publishing this should work too.

The only one that still fails is:

```
[FAIL] Could not process extension: {
  "id": "vshaxe.haxe-extension-pack",
  "repository": "https://github.com/vshaxe/vshaxe-extension-pack.git"
}
Error: Cannot resolve bundled extension: vshaxe.haxe-debug
```

That one shouldn't be too hard to fix either. I think it's just a matter of auto-publishing https://github.com/vshaxe/flash-debugger first.

**Comment by jankeromnes** [comment]
> The extension `kodetech.kha-extension-pack` failed, but the error looks more like an internal problem with this repository, and once resolved I believe publishing this should work too.

Actually it still fails with:

```
[FAIL] Could not process extension: {
  "id": "kodetech.kha-extension-pack",
  "repository": "https://github.com/Kode/vscode-kha-extension-pack"
}
Error: Cannot resolve dependency: kodetech.electron-debug
```

Should be resolved by https://github.com/open-vsx/publish-extensions/commit/1ea9becc622ca90d18e5f385646a3bb90d33074c (we'll know tomorrow).

> The only one that still fails is:
> [...] `vshaxe.haxe-extension-pack` [...]

Still fails, but with a different error now:

```
[FAIL] Could not process extension: {
  "id": "vshaxe.haxe-extension-pack",
  "repository": "https://github.com/vshaxe/vshaxe-extension-pack.git"
}
Error: Cannot resolve bundled extension: vshaxe.hxcpp-debugger
```

This should also get resolved, by https://github.com/open-vsx/publish-extensions/commit/e4b7c6ab2f02c7e52eaecce44973703ec20549c7

And finally, there is unfortunately still no news on `Jarrio.Haxe-Manager`'s license: https://github.com/Jarrio/Haxe-Manager/issues/17

**Comment by jankeromnes** [comment]
`kodetech.kha-extension-pack` also depends on https://github.com/Kode/vscode-krafix, which doesn't have a license. Will request a license there.

> `Error: Cannot resolve dependency: kodetech.electron-debug`

Now published: https://open-vsx.org/extension/kodetech/electron-debug

> `Error: Cannot resolve bundled extension: vshaxe.hxcpp-debugger`

Publishing failed due to missing dependency `haxe`:

```
Running: git clone --recurse-submodules https://github.com/vshaxe/hxcpp-debugger /tmp/repository
Running: git checkout 1.2.4
Running: npm install
Executing prepublish script 'npm run vscode:prepublish'...

> hxcpp-debugger@1.2.4 vscode:prepublish /tmp/repository
> haxe build.hxml

/bin/bash: haxe: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file /bin/bash
npm ERR! errno ENOENT
npm ERR! hxcpp-debugger@1.2.4 vscode:prepublish: `haxe build.hxml`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hxcpp-debugger@1.2.4 vscode:prepublish script.
```

**Comment by jankeromnes** [comment]
> > `Error: Cannot resolve bundled extension: vshaxe.hxcpp-debugger`
> 
> Publishing failed due to missing dependency `haxe`:
> 
> ```
> [...]
> ```
> 
> EDIT: Attempted to install it here https://github.com/open-vsx/publish-extensions/commit/68e7f630663ec32cc5165b32b05dc1b42ca2b9c7

Now failed with:

```
Running: git clone --recurse-submodules https://github.com/vshaxe/hxcpp-debugger /tmp/repository
Running: git checkout 1.2.4
Running: npm install
Running: npm install haxe
Executing prepublish script 'npm run vscode:prepublish'...

> hxcpp-debugger@1.2.4 vscode:prepublish /tmp/repository
> haxe build.hxml

Error: Error: Library vscode-debugadapter is not installed : run 'haxelib install vscode-debugadapter'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hxcpp-debugger@1.2.4 vscode:prepublish: `haxe build.hxml`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hxcpp-debugger@1.2.4 vscode:prepublish script.
```

Added the suggested command in https://github.com/open-vsx/publish-extensions/commit/d82a8b29bc24697d4c5ab89b583819e794b71767

**Comment by jankeromnes** [comment]
Now failed with:

```
Running: git clone --recurse-submodules https://github.com/vshaxe/hxcpp-debugger /tmp/repository
Running: git checkout 1.2.4
Running: npm install
Running: npm install haxe  && npx haxelib install vscode-debugadapter
Executing prepublish script 'npm run vscode:prepublish'...

> hxcpp-debugger@1.2.4 vscode:prepublish /tmp/repository
> haxe build.hxml

Error: Error: Library vscode is not installed : run 'haxelib install vscode'
```

The adventure continues!

**Comment by jankeromnes** [comment]
And now it failed with:

```
Running: git clone --recurse-submodules https://github.com/vshaxe/hxcpp-debugger /tmp/repository
Running: git checkout 1.2.4
Running: npm install
Running: npm install haxe && npx haxelib install vscode-debugadapter && npx haxelib install vscode
Executing prepublish script 'npm run vscode:prepublish'...

> hxcpp-debugger@1.2.4 vscode:prepublish /tmp/repository
> haxe build.hxml

src/Adapter.hx:4: characters 7-27 : Type not found : protocol.debug.Types
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

This is become a bit tedious. Maybe there are some official instructions somewhere how this should be packaged properly.

**Comment by jankeromnes** [comment]
@itzikiap Would you happen to know how to fix the `Type not found : protocol.debug.Types` error seen above that prevents `vshaxe.hxcpp-debugger` from being packaged?

**Comment by jankeromnes** [comment]
I've asked for help here: https://github.com/vshaxe/hxcpp-debugger/issues/26

**Comment by itzikiap** [comment]
I've closed the PR

**Pull request closed without merging**
