### PR TITLE
Upgrade haskell.haskell to 1.2.0

### PR DESCRIPTION
**Pull request by djcrock**
https://github.com/haskell/vscode-haskell/releases/tag/1.2.0

### CODE REVIEW

**Comment by spoenemann** [comment]
The haskell namespace has been claimed:
https://github.com/eclipse/open-vsx.org/issues/115

But the extension is still published by our script:
https://github.com/open-vsx/publish-extensions/commit/ceccdeda114b5aab76f15c5e1a861efc3dda14de

@jankeromnes do you remember why it is like that? @jaspervdj would you like to publish the extension yourself?

The extension is currently displayed with a warning because it has an owner, but is still published by our service account:
https://open-vsx.org/extension/haskell/haskell

**Comment by jankeromnes** [comment]
> The haskell namespace has been claimed:
> https://github.com/eclipse/open-vsx.org/issues/115
> 
> But the extension is still published by our script:
> https://github.com/open-vsx/publish-extensions/commit/ceccdeda114b5aab76f15c5e1a861efc3dda14de
> 
> @jankeromnes do you remember why it is like that?

Yes. This extension was added to our auto-publish list the day before the namespace was claimed:

Screenshot 2020-11-10 at 09 44 42

Screenshot 2020-11-10 at 09 44 58

@jaspervdj Please publish `haskell.haskell` `1.2.0` to OpenVSX (e.g. you can do so simply by running `npx ovsx publish`)

**Comment by spoenemann** [comment]
Ok, we should remove the entry from here, then.

**Comment by jankeromnes** [comment]
See also https://github.com/haskell/vscode-haskell/issues/250#issuecomment-676151903

**Comment by jankeromnes** [comment]
Seems like OpenVSX-publishing was already set up for `haskell.haskell` by @bubba.

But it was disabled again in https://github.com/haskell/vscode-haskell/commit/93e7b582b8c3094a5916cfa393c743ff6ca874b8 due to a missing `OPEN_VSX_ACCESS_TOKEN` token in Travis CI: https://github.com/haskell/vscode-haskell/issues/250#issuecomment-706739009

**Review by jankeromnes — APPROVED** [review]
I guess there is no harm in simply bumping our auto-published version while @jaspervdj and @bubba decide whether they want to take over the OpenVSX publishing.

**Pull request merged**
