### PR TITLE
Add C/C++ tools Extension

### PR DESCRIPTION
**Pull request by ImBearChild**
Add the official C/C++ extension from MS, which is under the MIT License.

### CODE REVIEW

**Review by jankeromnes — COMMENTED** [review]
Hi @ImBearChild, many thanks for your contribution! 🙏

However, while the repository of that extension is under MIT license, the extension itself is not:

https://marketplace.visualstudio.com/items/ms-vscode.cpptools/license

See also:
- https://github.com/open-vsx/publish-extensions/pull/98#issuecomment-665642077
- https://github.com/microsoft/vscode-cpptools/issues/6388

**Comment by ImBearChild** [comment]
Sorry for bothering you.🤣

**Comment by jankeromnes** [comment]
@ImBearChild Quite to the contrary! Please "bother" us with contributions any time. 😁

**Comment by ImBearChild** [comment]
Hello @jankeromnes ,

Sorry for bothering you again. But according to the new declaration made by the authors from MS, the source code of C/C++ tools extension is really under MIT now. They explain that additional binary files may be downloaded at runtime after the initial installation; these are governed by the more restrictive proprietary license terms found at RuntimeLicenses. 

So after the update of Licenses, I wonder can we publish it?

Thank you.

See:
https://github.com/microsoft/vscode-cpptools/issues/5784#issuecomment-755827652
https://github.com/microsoft/vscode-cpptools/blob/main/LICENSE.md

**Comment by spoenemann** [comment]
@ImBearChild the runtime license has not changed:
https://github.com/microsoft/vscode-cpptools/blob/main/RuntimeLicenses/cpptools-LICENSE.txt

It restricts usage to Microsoft products. We accept only open source licenses in this publishing repository.

**Pull request closed without merging**
