### PR TITLE
Add cup-lang.cup extension

### PR DESCRIPTION
**Pull request by jgrajewsky**

### CODE REVIEW

**Comment by akosyakov** [comment]
@jgrajewsky Please consider to reach out to the extension author first. Please see [why it is recommended.](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension).

The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You basically must get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82

**Comment by jgrajewsky** [comment]
I'm the author. Should I still follow [this](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)?

**Comment by akosyakov** [comment]
@jgrajewsky yes, it would be the best. Let us know if for some reasons it does not work for you.

**Comment by akosyakov** [comment]
Awesome!

**Pull request closed without merging**
