### PR TITLE
solution-explorer to handle sln-files

### PR DESCRIPTION
**Pull request by GitMensch**
licensed under CC-BY-SA-4.0

original request to publish at https://github.com/fernandoescolar/vscode-solution-explorer/issues/132 - if this happens we can still remove the CI entry again

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, thanks for this contribution! 👍

**Comment by GitMensch** [comment]
Did you register the namespace already? https://github.com/EclipseFdn/open-vsx.org/

**Comment by fernandoescolar** [comment]
I can't, it already exists...

**Comment by GitMensch** [comment]
Just create an issue on that place and it will be solved. Thank you taking the steps to publish the extension yourself, I'll remove it from the CI here which published it before (which is a "last resort" option in any case).

**Pull request merged**
