### PR TITLE
Add "ybaumes.highlight-trailing-white-spaces".

### PR DESCRIPTION
**Pull request by houhoulis**
Discussion & approval [here](https://github.com/yifu/highlight-trailing-whitespaces/pull/4#issuecomment-803466315).

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, many thanks! 🚀

**Comment by houhoulis** [comment]
thank you!

**Comment by jankeromnes** [comment]
Update: Auto-publishing worked! 🎉 https://open-vsx.org/extension/ybaumes/highlight-trailing-white-spaces

@houhoulis Please kindly confirm that the uploaded extension is working as intended.

**Comment by houhoulis** [comment]
ybaumes.highlight-trailing-white-spaces working as intended: highlighting trailing spaces in red except on the active line

🙌🏼  Perfect.

**Pull request merged**
