### PR TITLE
Update ms-python/python extension

### PR DESCRIPTION
**Pull request by gtsiolis**
This will update the ms-python/python extension to `2020.10.332292344`.

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, thanks! 🚀

**Comment by jankeromnes** [comment]
New extension version should get published in tonight's publish run 🙂

**Comment by gtsiolis** [comment]
Merci @jankeromnes!

**Comment by jankeromnes** [comment]
Worked! 🎉 https://open-vsx.org/extension/ms-python/python

**Comment by scollovati** [comment]
Hi, could you please update it to the latest version 2020.12.424452561 ?

**Comment by jankeromnes** [comment]
Aha, thanks @scollovati for pointing out that OpenVSX doesn't have the latest version!

- `extensions.json` already requests the latest version:

https://github.com/open-vsx/publish-extensions/blob/16ede16bf3c2100c5f7bdd37cee85c9ae9107af1/extensions.json#L887-L891

- however, the auto-republishing process now fails with this error:

```
Downloading https://github.com/microsoft/vscode-python/releases/download/2020.12.424452561/ms-python-release.vsix
[FAIL] Could not process extension: {
  "id": "ms-python.python",
  "download": "https://github.com/microsoft/vscode-python/releases/download/2020.12.424452561/ms-python-release.vsix",
  "version": "2020.12.424452561"
}
Error: Cannot resolve dependency: ms-toolsai.jupyter
```

That's why the latest version didn't make it to https://open-vsx.org/extension/ms-python/python

The solution would be to upload the missing dependency to OpenVSX. However, `ms-toolsai.jupyter`'s license doesn't seem to accept non-Microsoft registries:

https://marketplace.visualstudio.com/items/ms-toolsai.jupyter/license

**Comment by scollovati** [comment]
Hi @jankeromnes thanks for pointing it out. I wrote this two comments:

1. https://github.com/microsoft/vscode-python/pull/14430#issuecomment-753349867
2. https://github.com/microsoft/vscode-jupyter/pull/441#issuecomment-753350364

Hope that we get some clarification about this, otherwise the python extension will no more be updated for all the projects based on Open-VSX.

**Comment by scollovati** [comment]
Here you can find the reply: https://github.com/microsoft/vscode-jupyter/pull/441#issuecomment-754148125

> The Jupyter extension is designed to be used with the Microsoft Visual Studio Code product, and therefore uses a standard VS Code extension license, just like any other extensions in the marketplace. Its source code, as you pointed out, is fully open sourced under an MIT license.

So probably the best thing would be to re-build these core and widely used extensions as other forks have done for the IDE (Theia, Codium, ...).

**Pull request merged**
