### PR TITLE
Add cucumber support for ruby integration tests.

### PR DESCRIPTION
**Pull request by alexventuraio**

### CODE REVIEW

**Review by jankeromnes — COMMENTED** [review]
Many thanks for this contribution!

However, I don't see a `package.json` file in the root of the repository, so you probably want to add a `"location"` parameter to specify where the `package.json` can be found.

Additionally, I see two `package.json`s, one under `gclient` and one under `gserver`. Are these two separate extensions? In that case, I'd suggest adding two separate entries in `extensions.json` (same `"repository"`, different `"id"` and `"location"`).

**Comment by alexventuraio** [comment]
@jankeromnes I just did what you mentioned about the `location` parameter.
Please take a look and let me know if that could be enough for the build or if we need to implement anything else?
Thx! 🙏

**Review by jankeromnes — APPROVED** [review]
> @jankeromnes I just did what you mentioned about the `location` parameter.

Looks good, many thanks!

> Please take a look and let me know if that could be enough for the build or if we need to implement anything else?
> Thx! 🙏

Hmm, I don't fully understand how this extension should be packaged, but probably the most efficient way forward is to merge this and see how the publishing CI likes it (then we could iterate on any potential errors, or maybe it'll even work on first try 😁🤞).

**Comment by alexventuraio** [comment]
> > @jankeromnes I just did what you mentioned about the `location` parameter.
> 
> Looks good, many thanks!
> 
> > Please take a look and let me know if that could be enough for the build or if we need to implement anything else?
> > Thx! 🙏
> 
> Hmm, I don't fully understand how this extension should be packaged, but probably the most efficient way forward is to merge this and see how the publishing CI likes it (then we could iterate on any potential errors, or maybe it'll even work on first try 😁🤞).

@jankeromnes Jajaja neither do I. I don't fully understand how to build it but ok let's see what happen with the build after merging it and if we need some more fixes then we can start iterating until we get it fixed.

**Comment by jankeromnes** [comment]
@alexventuraio Aha, so, publishing did fail with this error log:

```
Running: git clone --recurse-submodules https://github.com/alexkrechik/VSCucumberAutoComplete /tmp/repository
Running: npm install
Executing prepublish script 'npm run vscode:prepublish'...

> cucumberautocomplete@2.15.0 vscode:prepublish /tmp/repository/gclient
> tsc -p ./

Error: src/extension.ts(3,23): error TS2307: Cannot find module 'path' or its corresponding type declarations.
Error: src/extension.ts(5,57): error TS2307: Cannot find module 'vscode' or its corresponding type declarations.
Error: src/extension.ts(6,85): error TS2307: Cannot find module 'vscode-languageclient' or its corresponding type declarations.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cucumberautocomplete@2.15.0 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the cucumberautocomplete@2.15.0 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-10-10T03_17_16_768Z-debug.log
[FAIL] Could not process extension: {
  "id": "alexkrechik.cucumberautocomplete",
  "repository": "https://github.com/alexkrechik/VSCucumberAutoComplete",
  "location": "gclient"
}
npm failed with exit code 2
```

Currently, the `npm install` is only run in the root of the extension, not in the `"location"` (`gclient/`).

Maybe we also need to add something like this to make it work?

```js
    "prepublish": "cd gclient && npm install"
```

**Comment by alexventuraio** [comment]
@jankeromnes I pushed the change you suggested, let's wait to see how it goes!

**Comment by alexventuraio** [comment]
@spoenemann @jankeromnes based on https://github.com/open-vsx/publish-extensions/pull/188#issuecomment-717045870 
Do you guys think we should rollback this extension until there's a clear way to build it?

**Comment by spoenemann** [comment]
If we don't get to a point where building the extension works, yes, we should remove it. Let's wait for a decision on https://github.com/alexkrechik/VSCucumberAutoComplete/issues/353 first. The optimal solution would be the original maintainers publishing the extension.

**Comment by alexventuraio** [comment]
Sounds great, let's wait a bit more to get a response from mainteners side!

**Pull request merged**
