### PR TITLE
Fix colon and add ionutvmi.reg

### PR DESCRIPTION
**Pull request by zmni**

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
Thanks for the contribution! Unfortunately we cannot accept the `reg-vscode` extension at the moment because it has no LICENSE file. Please ask the maintainer to choose an open source license (most extensions use MIT).

**Comment by jankeromnes** [comment]
License requested in https://github.com/ionutvmi/reg-vscode/issues/11

**Comment by ionutvmi** [comment]
the license has been added to the reg-vscode repository.

**Comment by jankeromnes** [comment]
Cool, many thanks @ionutvmi!

Also, please note that, while we're happy to auto-publish reg-vscode to OpenVSX from this repository, it is generally better for the owners to publish their extension directly:

- You can just run `npx ovsx publish` to do that (with a `OVSX_PAT` token from [here](https://open-vsx.org/user-settings/tokens) -- but there is no need to install anything else, as this will just use `vsce` like for the VSCode Marketplace)

- Extensions will be published from your account

If we auto-publish from here, extensions will appear with a yellow banner because they'll get published from our OpenVSX bot account.

**Comment by ionutvmi** [comment]
Hi @jankeromnes ,

Thank you, I followed the instructions and published it here: https://open-vsx.org/extension/ionutvmi/reg

**Comment by jankeromnes** [comment]
Hey, that's awesome, many thanks @ionutvmi! 🎉 🙏

You may also want to [claim](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace) the `ionutvmi` namespace on OpenVSX -- this will remove the yellow banner from https://open-vsx.org/extension/ionutvmi/reg

Since the extension is now published, I'll close this PR as resolved, but please let me know if we can help with anything OpenVSX-related -- we're always happy to help out. 🙂

**Pull request closed without merging**
