### PR TITLE
Add tomorrow theme

### PR DESCRIPTION
**Pull request by gbraad**
Not sure if this is correct, as the themes are all collected in this repo but divided into subfolders.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-TomorrowKit

License: MIT

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Thanks @gbraad!

> Not sure if this is correct, as the themes are all collected in this repo but divided into subfolders.

The syntax you've used looks correct. 👍 Also, if you wanted to add more themes, you'd need to add other similar entries (with different `"id"` and `"location"` but the same `"repository"`).

**Comment by gbraad** [comment]
>  you'd need to add other similar entries

I figured. Let's see if this works as expected. After this I will created the other entries.

**Comment by jankeromnes** [comment]
> I figured. Let's see if this works as expected. After this I will created the other entries.

Works for me, thanks!

Results should come in tonight at 03:03 UTC, so we'll know tomorrow whether publishing worked.

**Comment by jankeromnes** [comment]
Also, on a side note, you can add the other extensions like so:

```
node add-extension https://github.com/microsoft/vscode-themes --location=tomorrow
```

(This will automatically figure out the `"id"` and sort the list alphabetically 😇)

**Pull request merged**
