### PR TITLE
add "excalidraw-editor" extension

### PR DESCRIPTION
**Pull request by pomdtr**
I would love to be able to use my extension to edit schema directly on gitpod :)

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @pomdtr, sure! It would be awesome to have your extension on OpenVSX. 💯

One thought: Have you considered publishing yourself? I basically just a matter of running `npx ovsx publish` in your extension directory (this can even be automated with a GitHub Action).

If you're interested, you can learn more about self-publishing [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). Please let me know if you have any questions. 🙂

**Comment by jankeromnes** [comment]
Ping @pomdtr (happy to go either way, just waiting for your decision here 😊)

**Comment by pomdtr** [comment]
Oups, thanks for the reminder. I think I'll take the time to setup the github action, thanks a lot for the informations :)

**Comment by jankeromnes** [comment]
Awesome! Many thanks @pomdtr. 🙏 Please let me know if you'd like help with that (e.g. I'm happy to send you a PR 😊).

**Pull request closed without merging**
