### PR TITLE
WIP: Add Ariake Dark theme

### PR DESCRIPTION
**Pull request by aral**
This is a work-in-progress pull request to add the Ariake Dark theme to Open VSX.

Currently waiting for the author to post a license.

Issue: https://github.com/a-wart/ariake-dark/issues/7

The original theme that this is based on is released under the MIT license (https://github.com/pathtrk/ariake-dark-syntax).

I’ll remove the WIP prefix and leave a comment once the author has added a license.

### CODE REVIEW

**Comment by GitMensch** [comment]
Can you use "convert to draft" (upper-right corner) instead of/additional to the WIP prefix?

**Comment by gbraad** [comment]
Hi, still wanna add this theme?

**Comment by GitMensch** [comment]
Sure, as soon as the license is fixed - we maybe can just add it because of "the original one is MIT licensed"?

**Comment by filiptronicek** [comment]
Hey there @aral, is this PR still something you want to work on, or can I close the PR for the time being? I'm trying to clean the PRs up a bit.

**Comment by aral** [comment]
@filiptronicek Please feel free to close it; I don’t believe I’m still using this theme.

**Pull request closed without merging**
