### PR TITLE
[markdown lint] fix compilation of extension

### LINKED ISSUE #77: [markdownlint] non-working extension published
I just checked the latest and assume all versions are similarly non-working. I think it's due to requiring a non-standard way to build. Here's what worked for me:

```bash
npm install
npm run compile
vsce package
```
working extension size: ~150KB
non-working extension size: ~18k

### PR DESCRIPTION
**Pull request by marcdumais-work**
I hope this fixes #77

The default way of building this extension does not seem to result
in a working extension. Not sure what's missing, but it's much
smaller vs when fully built.

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>

### CODE REVIEW

**Comment by jankeromnes** [comment]
Unfortunately, a fixed extension will only get published after the next version bump (`> v0.36.1`), unless we delete the broken extensions from OpenVSX.

**Comment by marcdumais-work** [comment]
> Unfortunately, a fixed extension will only get published after the next version bump (`> v0.36.1`), unless we delete the broken extensions from OpenVSX.

+1 for deleting all (currently faulty) versions of this extension - they serve no useful purpose. Once done I expect that `v0.36.1` would be automatically re-published during the next nightly run?

**Comment by jankeromnes** [comment]
> +1 for deleting all (currently faulty) versions of this extension - they serve no useful purpose.

Agreed! @jbicker Are you able to delete extensions from https://open-vsx.org? We've noticed that all versions of https://open-vsx.org/extension/DavidAnson/vscode-markdownlint are broken, and would like to replace them with working versions.

> Once done I expect that `v0.36.1` would be automatically re-published during the next nightly run?

Yes, that's what indeed should happen after deletion.

**Comment by jbicker** [comment]
Hi, yes. I can delete them.

**Comment by jbicker** [comment]
Deleted

**Comment by jbicker** [comment]
Tomorrow is a new day for the markdown lint. :-)

**Comment by jankeromnes** [comment]
Awesome, many thanks @jbicker and @marcdumais-work! Yes, this will be a fresh start for markdown lint. 🙂

**Comment by jankeromnes** [comment]
New markdownlint is up! 🎉 https://open-vsx.org/extension/DavidAnson/vscode-markdownlint

Size looks correct too (150KB). Thanks again!

**Pull request merged**
