### PR TITLE
add GabrielNordeborn.vscode-rescript-relay

### LINKED ISSUE #488: Add RescriptRelay
I have the [authors permit](https://discord.com/channels/779997538434154497/842450522333380682/908040828411342869) to add the RescriptRelay extension here.

### PR DESCRIPTION
**Pull request by mellson**
Adding `GabrielNordeborn.vscode-rescript-relay` RescriptRelay with the [authors consent](https://discord.com/channels/779997538434154497/842450522333380682/908040828411342869). Fixes #488

### CODE REVIEW

**Comment by filiptronicek** [comment]
@mellson, please consider reaching out to the extension author first. Please see [why it is recommended.](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension).

The docs for publishing the extension are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions. Technically this should be straightforward. You basically must get a token and call `ovsx publish` with it. For example, this is how RedHat publishes their java extension: redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82

**Review by filiptronicek — CHANGES_REQUESTED** [review]
https://github.com/zth/vscode-rescript-relay/issues/32 needs to be closed first, but otherwise this is ready to merge

**Comment by filiptronicek** [comment]
@mellson sorry for mislabeling the extension as lacking of a license, it does indeed have it as I discovered today.

Because we want to minimize the number of extensions here, I have made an issue on the repo so maybe the maintainers can publish to OpenVSX directly. If they don't want to we can merge this here.

**Comment by filiptronicek** [comment]
https://github.com/zth/vscode-rescript-relay/issues/34 for further progress tracking.

**Comment by zth** [comment]
I have now published a version of the extension to ovsx. Do I need to do anything else?

**Pull request closed without merging**
