### PR TITLE
Add Rainbow CSV

### PR DESCRIPTION
**Pull request by mechatroner**
Please add my extension: "Rainbow CSV". By request from mechatroner/vscode_rainbow_csv#63

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @mechatroner! Thanks for your contribution.

We're of course happy to start auto-publishing "Rainbow CSV" from here, but I think it may be easier & preferable if you publish it yourself.

It's actually pretty simple:

1. Generate a `OVSX_PAT` token: https://open-vsx.org/user-settings/tokens

2. Run `npx ovsx publish` (no need to install or set up anything else)

Auto-publishing from here bears the risk of us accidentally publishing a broken extension (due to not fully understanding the building/packaging process of each extension), or failing to publish updates in a timely manner (we're trying our best, but are very few people and there are already many extensions in this list).

**Comment by mechatroner** [comment]
Thanks @jankeromnes ! I managed to publish my extension from a cloud VM ( it didn't work from my laptop, the npx command fails with mysterious `npm ERR! cb.apply is not a function` error, and I didn't have time to debug it ). Anyway, Rainbow CSV is now available in the registry: https://open-vsx.org/extension/mechatroner/rainbow-csv , woo-hoo! 
BTW Rainbow CSV doesn't require any packaging at all and no external libraries, so installing it is as easy as just cloning or copyiing the repo. I thought that your pipeline would handle this workflow automatically, that's why I suggested to add it to your auto-publish config.

**Comment by spoenemann** [comment]
@mechatroner great!

>  I thought that your pipeline would handle this workflow automatically, that's why I suggested to add it to your auto-publish config.

Yes it does, but the result would be that the extension is shown as "Published by @open-vsx". It's much better to have it published by original authors / maintainers.

The next step would be to take ownership of the `mechatroner` namespace as [described in the Wiki](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace). By this you can get rid of the yellow banner on top of the extension page.

**Comment by jankeromnes** [comment]
> Anyway, Rainbow CSV is now available in the registry: https://open-vsx.org/extension/mechatroner/rainbow-csv , woo-hoo!

Super cool! 🎉 Thanks a lot @mechatroner 

> ( it didn't work from my laptop, the npx command fails with mysterious `npm ERR! cb.apply is not a function` error, and I didn't have time to debug it )

Strange indeed. Maybe that's because of a too old Node.js version?

Anyway, since the extension is now officially published (🎉) I'll close this PR for now.

Please feel free to ping us any time, we're always happy to help with anything OpenVSX-related. 🙂

**Pull request closed without merging**
