### PR TITLE
Update prettier version.

### PR DESCRIPTION
**Pull request by alexventuraio**

### CODE REVIEW

**Review by jankeromnes — CHANGES_REQUESTED** [review]
Cool, many thanks for catching this!

However, this won't work because the vsix download URL still points to the old version.

Side note: you can open this repository in Gitpod, and run `node upgrade-extensions` to update extension versions semi-automatically (and then use `git add -p extensions` to only commit the changes that seem correct/desirable).

**Comment by alexventuraio** [comment]
Jajaja 😅 sorry for that @jankeromnes, I just wanted to move fast jajaja!
I've just fixed it!

And, I have never used `Gitpod` so I will do some research to use it, thanks! 🙏

**Review by jankeromnes — APPROVED** [review]
Looks good to me, many thanks!

**Comment by jankeromnes** [comment]
@alexventuraio You've probably noticed already, but the update worked! 🎉 https://open-vsx.org/extension/esbenp/prettier-vscode

Thanks again 👍

**Comment by alexventuraio** [comment]
Wohoo! Great! 👏🏻

**Pull request merged**
