### PR TITLE
Add a ayu theme to the flow.

### PR DESCRIPTION
**Pull request by alexventuraio**

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Sure! Thanks.

**Comment by jankeromnes** [comment]
FYI, publishing was successful! 🎉 https://open-vsx.org/extension/teabyii/ayu

**Comment by alexventuraio** [comment]
@jankeromnes what does this message means?
Screen Shot 2020-10-10 at 21 27 06

**Comment by spoenemann** [comment]
It means nobody has been assigned as owner of the namespace `teabyii`, see [this Wiki page](https://github.com/eclipse/openvsx/wiki/Namespace-Access).

**Pull request merged**
