### PR TITLE
[add extension] compare-folders

### PR DESCRIPTION
**Pull request by moshfeu**
Thanks :)

### CODE REVIEW

**Comment by moshfeu** [comment]
Thanks. I've created an issue. https://github.com/eclipse/open-vsx.org/issues/92

**Comment by jankeromnes** [comment]
Awesome! Thanks, and let me know if you need any help with the publishing. 👍

**Comment by moshfeu** [comment]
Thanks! 🚀

**Comment by moshfeu** [comment]
All done. Thank you :)
https://open-vsx.org/extension/moshfeu/compare-folders

**Comment by jankeromnes** [comment]
Super cool, many thanks for tackling this @moshfeu! 🚀

**Pull request closed without merging**
