### PR TITLE
feat(themes): Add synthwave theme

### PR DESCRIPTION
**Pull request by maxandersen**
maintainer have not responded on requests to publish directly thus making this PR.

https://github.com/robb0wen/synthwave-vscode/issues/185

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Awesome, many thanks @maxandersen for contacting the maintainers first. 💯

The auto-publish configuration looks exactly correct. 🎯 Can be merged as-is.

**Comment by maxandersen** [comment]
To be fair @pulberg did the reaching out. I just showed up noticing it been a year :)

Thanks for merging!

**Comment by jankeromnes** [comment]
@maxandersen Auto-publishing worked! 🎉 https://open-vsx.org/extension/RobbOwen/synthwave-vscode

Please confirm that the published extension works as expected.

**Comment by maxandersen** [comment]
It works! thanks @jankeromnes

**Pull request merged**
