### PR TITLE
Auto-publish hediet.vscode-drawio

### PR DESCRIPTION
**Pull request by mattburgess**

### CODE REVIEW

**Comment by jankeromnes** [comment]
Hi @mattburgess, many thanks for this contribution!

Note that this extension was also requested in https://github.com/open-vsx/publish-extensions/issues/51

Unfortunately, we cannot auto-publish it from this repository, because this extension is licensed under GPL-3.0, which is incompatible with the Eclipse Public License used by OpenVSX and associated tools: https://github.com/open-vsx/publish-extensions/issues/49#issuecomment-657778606

**Comment by mattburgess** [comment]
Ah; I skimmed that issue and thought it was waiting on some API compatibility issue to be resolved, I didn't click that it had actually been rejected on licensing grounds.

Does the restriction just mean that it can't be auto-published, or is it a stronger restriction meaning that even the upstream authors can't publish it to open-vsx at all?

**Comment by jankeromnes** [comment]
> Ah; I skimmed that issue and thought it was waiting on some API compatibility issue to be resolved, I didn't click that it had actually been rejected on licensing grounds.

That's likely our fault for not being super clear, because the questions around licenses were new to us as well.

> Does the restriction just mean that it can't be auto-published, or is it a stronger restriction meaning that even the upstream authors can't publish it to open-vsx at all?

Good question. @spoenemann do you know what would happen if the author of a GPL-3.0 licensed extension wants to publish the extension to OpenVSX?

**Comment by spoenemann** [comment]
I think it doesn't matter who publishes the extension. The restriction is really about the license.

**Comment by spoenemann** [comment]
Closing due to incompatible license.

**Comment by jankeromnes** [comment]
@mattburgess Good news! The Eclipse board may soon allow all "standard" open-source licensed extensions onto OpenVSX. While no official final decision has been announced yet, we consider this to be very promising, and have decided to accept your contribution now. Many thanks!

**Pull request merged**
