### PR TITLE
add jigar-patel.OdooSnippets

### PR DESCRIPTION
**Pull request by yajo**
- [x] I have read the note above about PRs contributing or fixing extensions
- [x] I have tried reaching out to the extension maintainers about publishing this extension to OpenVSX: https://github.com/Droggol/VscOdooSnippets/issues/47
- [x] This extension has an [OSI-approved OSS license](https://opensource.org/licenses) (we don't accept proprietary extensions in this repository)

## Description

add jigar-patel.OdooSnippets extension

### CODE REVIEW

**Comment by filiptronicek** [comment]
Hi @yajo 👋, huge thanks for the contribution! I'd like to wait some more time before we merge this to maybe let @jat-odoo publish on their own :).

**Comment by jat-odoo** [comment]
Hi @yajo,

I just quickly read the [documentation](https://github.com/open-vsx/publish-extensions#when-to-add-an-extension) about open-vsx. 
So, I will publish it from my side as it would be more beneficial for the long term.

BTW, Thanks 👍

**Comment by yajo** [comment]
Thank you, I hope you can do it soon, I'm really missing this extension.

**Comment by filiptronicek** [comment]
@jat-odoo let me know if you need any help getting this set up. https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md is a good guide describing the whole process.

I'll leave this PR open until it is published.

**Comment by jat-odoo** [comment]
@filiptronicek @yajo

Deployed on Open VSX
Extension: https://open-vsx.org/extension/jigar-patel/OdooSnippets
Namespace Requested: https://github.com/EclipseFdn/open-vsx.org/issues/1018

Thanks.

**Comment by filiptronicek** [comment]
Thanks a lot for publishing, @jat-odoo!

**Pull request closed without merging**
