### PR TITLE
Add jianbingfang.dupchecker

### PR DESCRIPTION
**Pull request by condemil**
Add jianbingfang.dupchecker

### CODE REVIEW

**Review by jankeromnes — COMMENTED** [review]
Many thanks for this contribution!

Looks good to me, except the extension doesn't specify a license, while a valid open-source license is required to publish to https://open-vsx.org

I've requested a license here: https://github.com/jianbingfang/vscode-dup-checker/issues/12

**Review by jankeromnes — APPROVED** [review]
License was clarified (MIT): https://github.com/jianbingfang/vscode-dup-checker/commit/b1490245428fdcca8cccc18c85c674db1417f765 🎉

**Comment by jankeromnes** [comment]
Ah, but the license wasn't part of the previous release, so re-publishing that release failed:

```
[FAIL] Could not process extension: {
  "id": "jianbingfang.dupchecker",
  "download": "https://github.com/jianbingfang/vscode-dup-checker/releases/download/v0.1.6/dupchecker-0.1.6.vsix",
  "version": "0.1.6"
}
Error: This extension cannot be accepted because it has no license.
```

@condemil @jianbingfang FYI This extension can only be published to https://open-vsx.org when there is a new release (including the license) and we update our reference here.

**Comment by jianbingfang** [comment]
Just published v0.1.7 with license in it, please have a try @jankeromnes .

**Comment by jankeromnes** [comment]
Awesome, many thanks @jianbingfang!

Our weekly `upgrade-extensions` script should pick that up automatically in Sunday's upgrade run. 🙂

**Comment by condemil** [comment]
Thanks @jankeromnes and @jianbingfang for helping out!

**Pull request merged**
