### PR TITLE
Add fabiospampinato.vscode-highlight extension

### PR DESCRIPTION
**Pull request by fabienleite**
Hi ! 

Thanks for the great work. An extension I used quite a lot on vscode so it would be nice to have on the store for the use with more open editors. 😄

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Approved! Many thanks for your contribution! 🥇

**Comment by jankeromnes** [comment]
Oops @fabienleite, it seems that auto-publishing this extension failed with these errors:

```
Running: git clone --recurse-submodules https://github.com/fabiospampinato/vscode-highlight /tmp/repository
Running: npm install
Executing prepublish script 'npm run vscode:prepublish'...

> vscode-highlight@1.4.1 vscode:prepublish /tmp/repository
> rm -rf out && webpack --mode production

Hash: 2a6b13703471ab87d5be
Version: webpack 4.46.0
Time: 3992ms
Built at: 02/15/2021 3:33:25 AM
 2 assets
Entrypoint main = extension.js extension.js.map
[0] external "vscode" 42 bytes {0} [built]
[1] ./src/decorator.ts 6.97 KiB {0} [built]
[2] ./src/extension.ts 679 bytes {0} [built]
[3] ./src/changes.ts 891 bytes {0} [built]
[5] (webpack)/buildin/module.js 497 bytes {0} [built]
[7] ./src/config.ts 304 bytes {0} [built]
[8] ./src/utils.ts 1.11 KiB {0} [built]
    + 2 hidden modules

ERROR in /tmp/repository/node_modules/@types/node/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/base.d.ts(10,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/base.d.ts(11,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/base.d.ts(12,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/base.d.ts(13,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts(10,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts(11,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts(12,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/ts3.6/base.d.ts(13,1)
      TS1084: Invalid 'reference' directive syntax.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(21,30)
      TS1005: '=' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(134,24)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(135,13)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(135,23)
      TS1005: ',' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(138,13)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(138,28)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(148,24)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(149,13)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(149,23)
      TS1005: ',' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(152,13)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/util.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/util.d.ts(152,23)
      TS1005: '(' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(2,68)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(35,68)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(44,94)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(44,101)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(44,104)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(46,98)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(46,105)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(46,108)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(54,47)
      TS1144: '{' or ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(54,53)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(54,56)
      TS1005: ';' expected.

ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts
[tsl] ERROR in /tmp/repository/node_modules/@types/node/assert.d.ts(81,61)
      TS1005: ';' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-highlight@1.4.1 vscode:prepublish: `rm -rf out && webpack --mode production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-highlight@1.4.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Looks similar to https://github.com/open-vsx/publish-extensions/pull/286#issuecomment-779093302

**Comment by andhet** [comment]
The output from _npm -ddd run compile_ is:
```
Running: git clone --recurse-submodules https://github.com/fabiospampinato/vscode-highlight /home/runner/repository
Running: npm install
Running: npm -ddd run compile
error: Error: Command failed: npm -ddd run compile
Running: rm -rf /home/runner/repository /home/runner/download
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   '/opt/hostedtoolcache/node/12.20.1/x64/bin/node',
npm verb cli   '/opt/hostedtoolcache/node/12.20.1/x64/bin/npm',
npm verb cli   '-ddd',
npm verb cli   'run',
npm verb cli   'compile'
npm verb cli ]
npm info using npm@6.14.10
npm info using node@v12.20.1
npm verb run-script [ 'precompile', 'compile', 'postcompile' ]
npm info lifecycle vscode-highlight@1.4.1~precompile: vscode-highlight@1.4.1
npm info lifecycle vscode-highlight@1.4.1~compile: vscode-highlight@1.4.1
npm verb lifecycle vscode-highlight@1.4.1~compile: unsafe-perm in lifecycle true
npm verb lifecycle vscode-highlight@1.4.1~compile: PATH: /opt/hostedtoolcache/node/12.20.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/runner/repository/node_modules/.bin:/opt/hostedtoolcache/Python/3.8.7/x64/bin:/opt/hostedtoolcache/Python/3.8.7/x64:/opt/hostedtoolcache/node/12.20.1/x64/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
npm verb lifecycle vscode-highlight@1.4.1~compile: CWD: /home/runner/repository
npm sill lifecycle vscode-highlight@1.4.1~compile: Args: [ '-c', 'webpack --mode development' ]
npm sill lifecycle vscode-highlight@1.4.1~compile: Returned: code: 2  signal: null
npm info lifecycle vscode-highlight@1.4.1~compile: Failed to exec compile script
npm verb stack Error: vscode-highlight@1.4.1 compile: `webpack --mode development`
npm verb stack Exit status 2
npm verb stack     at EventEmitter.<anonymous> (/opt/hostedtoolcache/node/12.20.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:314:20)
npm verb stack     at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/12.20.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1022:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid vscode-highlight@1.4.1
npm verb cwd /home/runner/repository
npm verb Linux 5.4.0-1039-azure
npm verb argv "/opt/hostedtoolcache/node/12.20.1/x64/bin/node" "/opt/hostedtoolcache/node/12.20.1/x64/bin/npm" "-ddd" "run" "compile"
npm verb node v12.20.1
npm verb npm  v6.14.10
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! vscode-highlight@1.4.1 compile: `webpack --mode development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the vscode-highlight@1.4.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 2, true ]
```
I have the same output on my machine. 
@jankeromnes 
I think you have some javascript/typescript knowledge. Have you an idea?

**Comment by jankeromnes** [comment]
@spoenemann Do you remember who we fixed similar-looking `@types` errors for other extensions in the past?

**Comment by spoenemann** [comment]
No I don't. It could be a mismatch of typescript / node versions.

**Comment by AndrewKvalheim** [comment]
Related: fabiospampinato/vscode-highlight#83

**Pull request merged**
