### PR TITLE
Add extension halcyontechltd.vscode-rpgle

### PR DESCRIPTION
**Pull request by chrjorgensen**

### CODE REVIEW

**Comment by filiptronicek** [comment]
Hey there @chrjorgensen, have you pleased checked with the author that they are not willing to publish the extension themselves? If not, we should create an issue in the repo in accordance to https://github.com/open-vsx/publish-extensions#when-to-add-an-extension.

**Comment by chrjorgensen** [comment]
Hi @filiptronicek 

I asked the author back in Spring 2021 to publish the main extension "halcyontechltd.code-for-ibmi" to Open VSX, which hasn't happened yet (have just [asked again](https://github.com/halcyon-tech/vscode-ibmi/issues/126#issuecomment-1005743971)).

This extension is a spin-off of the main extension, so I just wanted the code back into Open VSX - but I agree that it would be best if the author published it himself.

If you reject this PR I can still use the spin-off extension - but have to download it manually from the MS marketplace instead.

So it's up to you - I'll accept any decision you make. :-)

**Comment by filiptronicek** [comment]
Hi @worksofliam 👋, glad to see that you are preparing to publish the extension to OpenVSX, at least for https://github.com/halcyon-tech/vscode-ibmi, so that makes me wonder if you are willing to do the same for the repo which this issue is about, https://github.com/halcyon-tech/vscode-rpgle. I would greatly appreciate it and it would really make things easier for us!

P.S. If your namespace takes too long to claim please ping me so we can close this 🙂, I'll reach out to the maintainters.

**Comment by worksofliam** [comment]
@filiptronicek I will eventually get around to publishing there, as soon as I am able to publish vscode-ibmi.

You can close this 😄 !

Thanks!

**Pull request closed without merging**
