### PR TITLE
Add Erlang LS extension

### PR DESCRIPTION
**Pull request by chintan-mishra**
Add plugins for supporting Erlang

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Great addition! Many thanks @chintan-mishra 👍

**Comment by chintan-mishra** [comment]
Thank you for the kind words😀

**Comment by jankeromnes** [comment]
Auto-publishing worked! 🎉 https://open-vsx.org/extension/erlang-ls/erlang-ls

Please kindly confirm that the uploaded extension works as expected 🙏

**Comment by chintan-mishra** [comment]
@jankeromnes 

I rigged up the `ErlangLS` system locally, and I was using the `ErlangLS` repository directly. However, the linked repo is not the plugin to be used within `VSCode-OSS`. The repository and process are slightly different. I am working on a patch as you are reading this comment.

The name of `ErlangLS` plugin are of the following format: `erlang-ls-0.0.15.vsix`. I am planning to direct the auto-publishing tool to use the wildcard filename whenever a new `.vsix` file is built. In order to do this, I will be using `extensionFile: erlang-ls-*.vsix` in the section defining this tool. What are the possible ramifications of this step?

**Pull request merged**
