### PR TITLE
Add rheller.alive

### PR DESCRIPTION
**Pull request by tani**
- [x] I have read the note above about PRs contributing or fixing extensions
- [x] I have tried reaching out to the extension maintainers about publishing this extension to Open VSX (if not, please create an issue in the extension's repo using [this template](https://github.com/open-vsx/publish-extensions/blob/HEAD/docs/external_contribution_request.md)).
- [x] This extension has an [OSI-approved OSS license](https://opensource.org/licenses) (we don't accept proprietary extensions in this repository)

## Description

- Someone tried to reaching out the thextension maintainers about publishing this extension to Open VSX (https://github.com/nobody-famous/alive/issues/183)
- This extension is licensed under the Public Domain (https://github.com/nobody-famous/alive#license)

### CODE REVIEW

**Comment by tani** [comment]
@filiptronicek Would you mind to give the approval to test package?

**Comment by filiptronicek** [comment]
Hi @tani 👋, it looks like it builds fine but `ovsx` requires there to be a LICENSE either as a file or inside of the `package.json`. Could you raise a request to include it there? Compatible license slugs can be found [here](https://spdx.org/licenses/).

**Comment by tani** [comment]
Hi @filiptronicek, thank you for pointing the issue. I have asked him to update LICENSE to be OSI-approved. Now, what's a good news, that he update the license, The Unlicense 🎉

**Comment by tani** [comment]
@filiptronicek

This is a friendly reminder to please re-run GitHub CI/CD.

Thank you!

**Review by filiptronicek — APPROVED** [review]
Looks great, thanks

**Pull request merged**
