### PR TITLE
Add Nix language support

### PR DESCRIPTION
**Pull request by 1000101**
Add Nix language support as it's currently missing in OVSX registry - https://github.com/bbenoist/vscode-nix/issues/7

### CODE REVIEW

**Review by spoenemann — APPROVED** [review]
Thanks. However, we should remove this entry again in case @bbenoist decides to publish the extension.

**Comment by 1000101** [comment]
I've just found out that there is a better, up-to-date initiative in https://github.com/nix-community/vscode-nix-ide/issues/17/ so once it gets published this PR can be reverted in its favor. Sorry for the fuss!!!

**Comment by spoenemann** [comment]
Ok I'll revert the commit.

**Comment by 1000101** [comment]
Thank you so much!

**Pull request merged**
