### PR TITLE
Add Zenburn, and 2 OCaml extensions

### PR DESCRIPTION
**Pull request by edwintorok**

### CODE REVIEW

**Comment by spoenemann** [comment]
Thanks for the contribution!

`hc-zenburn-vscode` has no license. I opened https://github.com/drzix/hc-zenburn-vscode/issues/4 to address this, but we have to wait until that is done before we can add it to Open VSX.

`vscode-reasonml` says in its README that it's currently unmaintained. Do you think it is still useful?

Generally it would be good to add `checkout` properties with the respective release tags to all new entries. This ensures that we build from exactly the sources that were used for the version we want to install.

**Comment by edwintorok** [comment]
Indeed vscode-reasonml is deprecated and doesn't work with recent versions of OCaml anymore, I removed it from this PR.
There is an alternative linked from its github page, and I opened an issue to get it added to open-vsx.org: https://github.com/jaredly/reason-language-server/issues/465. It is not as simple as adding to package.json because package.json is missing some fields.

**Comment by edwintorok** [comment]
A license file has been added for hc-zenburn-vscode, and I've added a checkout property for ocamllabs.ocaml-platform,  so hopefully this PR is good to go now? (hc-zenburn-vscode has no tags, so I could only add a hash as checkout, not sure if that'd be useful)

**Comment by spoenemann** [comment]
@drzix chose GPL-3.0 for hc-zenburn-vscode. Unfortunately that license is not compatible with requirements of the Eclipse Foundation at this moment, see https://github.com/open-vsx/publish-extensions/issues/49#issuecomment-657778606.

@edwintorok could you remove that extension from this PR? We might be able to include GPL licensed extensions at some point, for now we should stick with the current requirements.

**Comment by edwintorok** [comment]
I intended to use hc-zenburn-vscode with Codium which is MIT licensed and therefore compatible with GPL3. It'd be nice if open-vsix had a way of accepting GPL3 extensions for the purposes of Codium (and hide it from Eclipse if it has to).

Anyway I've replaced that plugin with another one that is MIT licensed (it is not the high-contrast version).

**Review by spoenemann — APPROVED** [review]

**Comment by spoenemann** [comment]
> It'd be nice if open-vsix had a way of accepting GPL3 extensions for the purposes of Codium

I agree. We might get back to this in case the requirements will change.

**Comment by jankeromnes** [comment]
Update: Auto-publishing worked! 🎉 
- https://open-vsx.org/extension/ocamllabs/ocaml-platform
- https://open-vsx.org/extension/ryanolsonx/zenburn

> It'd be nice if open-vsix had a way of accepting GPL3 extensions for the purposes of Codium

I agree as well. FYI, we're currently investigating a solution that could potentially allow any open-source license onto OpenVSX. If it works, you can expect more news on that in a few weeks or so.

**Pull request merged**
