### PR TITLE
Add arjun.swagger-viewer to extensions.json

### PR DESCRIPTION
**Pull request by tchernobog**

### CODE REVIEW

**Review by jankeromnes — APPROVED** [review]
Looks good to me, many thanks! 👍

**Comment by jankeromnes** [comment]
Unfortunately, auto-publishing failed here as well:

```
Running: git clone --recurse-submodules https://github.com/arjun-g/vs-swagger-viewer /tmp/repository
Running: npm install
Executing prepublish script 'npm run vscode:prepublish'...

> swagger-viewer@3.0.1 vscode:prepublish /tmp/repository
> tsc -p ./

##[error]src/preview/client.ts(101,30): error TS2339: Property 'swagger' does not exist on type 'string | object'.
  Property 'swagger' does not exist on type 'string'.
##[error]src/preview/client.ts(104,28): error TS2339: Property 'openapi' does not exist on type 'string | object'.
  Property 'openapi' does not exist on type 'string'.
##[error]src/preview/client.ts(105,28): error TS2339: Property 'openapi' does not exist on type 'string | object'.
  Property 'openapi' does not exist on type 'string'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
Running: rm -rf /tmp/repository /tmp/download
npm ERR! swagger-viewer@3.0.1 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the swagger-viewer@3.0.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by tchernobog** [comment]
There seem to be a missing type coercion from upstream, I will open a separate issue. Thanks!

**Comment by tchernobog** [comment]
Depends on the status of https://github.com/arjun-g/vs-swagger-viewer/pull/94

**Pull request merged**
